services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cookbook_admin
      POSTGRES_PASSWORD: adhdagagA2@
      POSTGRES_DB: cookbook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cookbook_admin -d cookbook_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"  # Expose directly so you can hit /metrics and /docs
    environment:
      - DOCKER_ENV=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    command: celery -A app.services.newsletter.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    
  beat:
    build: .
    command: celery -A app.services.newsletter.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
